### PR TITLE
Rename options to choices throughout the solution

### PR DESCRIPTION
**Pull request by stevenhillcox**

### CODE REVIEW

**Comment by stevenhillcox** [comment]
Protractor tests updated and pass

**Comment by JDawes-ScottLogic** [comment]
:speech_balloon: :arrow_up:

**Comment by JDawes-ScottLogic** [comment]
Foreign Keys are given a deterministic name by Entity Framework, so this is fine (It's Default Constraints that aren't).

**Comment by stevenhillcox** [comment]
FK does not need to cascade on delete. This would imply deleting a vote for an option/choice should delete the option/choice.

Merge conflict resolved

**Comment by JDawes-ScottLogic** [comment]
:+1: :shipit:

**Pull request merged**
