### PR TITLE
Fix/remove automigrations

### PR DESCRIPTION
**Pull request by stevenhillcox**

### CODE REVIEW

**Comment by stevenhillcox** [comment]
All tests pass and functionality appears to have been retained.
As with all PRs that change the DB, might want to look over this one carefully.

**Comment by JDawes-ScottLogic** [comment]
Can't see an actual file rename for 2d655bb? Just looks like a rename in the project.

**Comment by JDawes-ScottLogic** [comment]
Apparently `git mv -f file File` will force a rename with the uppercase.

**Comment by JDawes-ScottLogic** [comment]
:+1: :shipit:

**Pull request merged**
