### PR TITLE
Feature/disable revotes

### PR DESCRIPTION
**Pull request by stevenhillcox**

### CODE REVIEW

**Comment by JDawes-ScottLogic** [comment]
:speech_balloon: :arrow_up: @stevenhillcox

**Comment by JDawes-ScottLogic** [comment]
After conversations with Dave, there isn't a need for all the options on the front end to be "off" by default. My opinions on the naming are above. @tpkelly would you like to weigh in and give an opinion?

**Comment by JDawes-ScottLogic** [comment]
Further conversations with Dave indicate that this behavior isn't what he was envisioning...

**Comment by stevenhillcox** [comment]
Locking this until Dave is happy.

**Pull request closed without merging**
