### PR TITLE
Set new manage Guid when ballots are created

### PR DESCRIPTION
**Pull request by stevenhillcox**

### CODE REVIEW

**Comment by tpkelly** [comment]
Can we add a unit test for this?

**Comment by tpkelly** [comment]
Fixes both VA-361 and VA-362. We should probably mark one as a duplicate of the other

**Comment by stevenhillcox** [comment]
This does not fix VA-361. That is addressed in https://github.com/Generic-Voting-Application/voting-application/pull/328

**Comment by tpkelly** [comment]
Good to go when appveyor is happy

**Pull request merged**
